Repository kaikim97/CS492, pull requests merged in 2021-12, with the labels that each got.

#19 Update README.md
  README.md
Labels: documentation

#21 preoccupancy implemented
  server/createData.js
  server/models/hall.js
  server/models/reservation.js
  server/routes/halls.js
  server/routes/reservations.js
Labels: enhancement

#22 fixed error that deletes valid reservation
  server/routes/halls.js
Labels: bug

#24 Backend
  README.md
  server/createData.js
  server/models/hall.js
  server/models/reservation.js
  server/routes/halls.js
  server/routes/reservations.js
Labels: documentation, enhancement
